### ISSUE TITLE
pip install extras for awkward and parquet

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#293]
Needs pyarrow and fsspec along with awkward.
Same with pandas

See if awkward install accepts extras

**Comment by talvandaalen** [comment]
Pyarrow and pandas are listed in the pyproject.toml file, but as optional - is that correct?

**Comment by alexander-held** [comment]
I agree that the `pandas` handling might need an update: when running e.g. https://github.com/ssl-hep/ServiceX_frontend/blob/8c3f266c74f93eec91499dc8974e25224e4cf19a/examples/single_file_uproot.py which uses `as_pandas()` without `pandas` installed (since it is an optional dependency currently), the trace ends up being 
```pytb
  File "[...]/ServiceX_frontend/servicex/dataset.py", line 457, in as_pandas_async
    dataframes = pd.concat(
                 ^^
NameError: name 'pd' is not defined. Did you mean: 'id'?
```
and should include some more informative message telling the user to install `pandas` ideally.

**Comment by gordonwatts** [comment]
Agreed. `awkward` has a nice import error message (and import utility that generates it I think). That might be a way to go.
