### ISSUE TITLE
`tree-name` needs to be passed to ServiceX as an extra option

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#47]
The uproot back end needs an extra bit of info here - `tree-name`.

- How do pass extra meta-data in general?
- how to pass `tree-name` specifically?

**Comment by BenGalewsky** [comment]
Can this be included in the qastle query? Best if it's not part of the transform JSON document, but inside the query itself

**Comment by gordonwatts** [comment]
@masonproffitt - what do you think of this idea? We are trying to make the interface to ServiceX more uniform.

**Comment by masonproffitt** [comment]
What idea do you mean exactly? As I mentioned on Slack, this feature already exists within func_adl.uproot. All you have to do is use `EventDataset(None, 'tree_name')` (or the qastle equivalent `(Call 'EventDataset' None 'tree_name')`). The `None` is necessary because the second argument is the filename, which ServiceX passes as an argument of the func_adl-generated function instead.

**Comment by gordonwatts** [comment]
Ah - that is terrific. I had thought that currently the 'tree-name' was passed in via the `servicex` request. I think we can close this and continue on slack.
